### ISSUE TITLE
FaceGenData directories analyzed as plugins

### ISSUE THREAD

**Issue by KerningChameleon** [matortheeternal/mod-analyzer#18]
Attempted Analysis of [Konahriks Accoutrements - Dragon Priest Armory](http://www.nexusmods.com/skyrim/mods/32458/) with Mod Analyzer 1.9.1 through Mod Organizer 1.3.11 on Windows 10 (1607). Analysis fails with FOMOD main archive with this error [(full log on pastebin due to length)](http://pastebin.com/MwkjFT4V):

> Getting plugin dump for 00 - REQUIRED FILES\meshes\actors\character\FaceGenData\FaceGeom\konahrik_accoutrements.esp...
> Extracting 00 - REQUIRED FILES\meshes\actors\character\FaceGenData\FaceGeom\konahrik_accoutrements.esp...
> Analyzing 00 - REQUIRED FILES\meshes\actors\character\FaceGenData\FaceGeom\konahrik_accoutrements.esp...
> 
> Target file not found.
>  
> 
> Plugin dump failed.
>    at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeEntries()
>    at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
> Analysis failed.

Same result when run as either FOMOD or BAIN, as well as if analyzed standalone or with optional archives.

**Comment by matortheeternal** [comment]
Seems that extracting a plugin isn't working properly?  I'll try to analyze it myself to see if I can recreate the issue.

**Comment by matortheeternal** [comment]
Actually, just noticed what this is.  I've seen this myself as well, it's because directories are being mapped to FOMOD mod options, and facegendata/facegeom folders are named with a .esp/.esm extension.  I need to figure out how to avoid that.

EDIT: If these directories are empty that could cause ModAnalyzer to mistakenly think they are plugin files.  I've written some code as part of the `__MACOSX` handling to ignore plugin paths that are under `actors\charactrer\FaceGenData\`.
